version: "3.9"

services:
  angular-fe-dev:
    container_name: DEVfrontend
    build:
      context: ./batch-demo-fe/
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./batch-demo-fe/:/usr/src/app

  postgres-dev:
    container_name: DEVpostgres
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: batch_user
      POSTGRES_PASSWORD: Spr1ngB@tchDem0us3r
      POSTGRES_DB: spring_batch_item_generator
    ports:
      - "5432:5432"
